### ISSUE TITLE
The purpose of gen_test object in FUNITModel

### ISSUE THREAD

**Issue by NTU-P04922004** [NVlabs/FUNIT#37]
The `gen_test` object in `FUNITModel` seems to be a clone of the whole model except the discriminator. The `gen_test` object is only used in generating testing results and it seems that it is redundant because we can run the gen object in evaluation mode. Why making a clone of the gen object? Was it designed for the multi-GPU environment?

https://github.com/NVlabs/FUNIT/blob/4cd5f22cc330bbf1804db7d5364e870e412c324a/funit_model.py#L23

**Comment by edward3862** [comment]
@NTU-P04922004 

I find the answer in the paper.

> The ﬁnal generator is a historical average version of the intermediate generators where the update weight is 0.001.

https://github.com/NVlabs/FUNIT/blob/4cd5f22cc330bbf1804db7d5364e870e412c324a/trainer.py#L18

**Comment by NTU-P04922004** [comment]
> @NTU-P04922004
> 
> I find the answer in the paper.
> 
> > The ﬁnal generator is a historical average version of the intermediate generators where the update weight is 0.001.
> 
> https://github.com/NVlabs/FUNIT/blob/4cd5f22cc330bbf1804db7d5364e870e412c324a/trainer.py#L18

Got it, thanks!
