### ISSUE TITLE
Dataset download link is broken

### ISSUE THREAD

**Issue by MasterXiYu** [NVlabs/FUNIT#38]
Can you upload a dataset to google Drive？Thanks a lot

**Comment by MasterXiYu** [comment]
I get a link from baiduyun download

**Comment by edward3862** [comment]
@MasterXiYu 
Hi, I'm looking for the dataset too. Could you please provide a baiduyun download link? Thanks.

**Comment by MasterXiYu** [comment]
https://pan.baidu.com/s/1NT2uSw008gXqQZGmzAv4sQ 提取码：5qaa only 7days

**Comment by MasterXiYu** [comment]
sorry, I lost it
