### ISSUE TITLE
GANimal demo is broken when uploading an image

### ISSUE THREAD

**Issue by nbeuchat** [NVlabs/FUNIT#49]
Hello! Not sure if this is the correct place to report this. In any case, I cannot use the GANimal Demo on http://imaginaire.cc/ganimal/ as when I click on Upload after selecting an image, it throws an error:

```
Uncaught ReferenceError: loadImage is not defined
    onclick http://imaginaire.cc/ganimal/:1
```

I have the same problem on Firefox (96.0) and Google Chrome (95.0.4638.54)

**Comment by mingyuliutw** [comment]
Thanks for reporting the issue. It should be fixed now. Please try again and let me know if it is not the case.

**Comment by nbeuchat** [comment]
That was fast, thanks! It works fine now
